version: '3.6'

services:
  mysql:
    image: mysql:latest
    container_name: artinus-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: artinus
      MYSQL_USER: artinus
      MYSQL_PASSWORD: artinus
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    networks:
      - app-network
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis:latest
    container_name: artinus-redis
    ports:
      - 6380:6379
    networks:
      - app-network

  app:
    image: artinus:latest
    container_name: artinus
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/artinus?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: artinus
      SPRING_DATASOURCE_PASSWORD: artinus
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      TZ: Asia/Seoul
    depends_on:
      - mysql
      - redis
    ports:
      - 8081:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
