version: '3.6'

services:
  mysql:
    image: mysql:latest
    container_name: artinus-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: artinus
      MYSQL_USER: artinus
      MYSQL_PASSWORD: artinus
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    networks:
      - app-network
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

  app:
    image: artinus:latest
    container_name: artinus
    environment:
      TZ: Asia/Seoul
    depends_on:
      - mysql
    ports:
      - 8081:8080

networks:
  app-network:
    driver: bridge
