spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3307/artinus?serverTimezone=Asia/Seoul
    username: artinus
    password: artinus
    driver-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level.org.hibernate:
    SQL: DEBUG
    orm.jdbc.bind: TRACE
